version: '3'
services:
  simple_crud:
    image: crud
    working_dir: /app
    command: poetry run flask run --host=0.0.0.0 --debug
    environment:
      ENVIRONMENT: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    networks:
      - minha-rede

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha
      MONGODB_DATABASE: tcc
      MONGODB_QUIET: true
    networks:
      - minha-rede

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha
      ME_CONFIG_MONGODB_URL: mongodb://root:senha@mongo:27017/
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
